name: C++ CI Calculator

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2c

    - name: Setup CMmake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Create a build directory
      run: |
        mkdir build
        cd build

    - name: Configure CMake
      run: cmake ..

    - name: Build
      run: cmake --build .

    - name: Run Test Cases
      run: ctest

 